src/Entity/Oferta.php
<?php

namespace App\Entity;

use App\Repository\OfertaRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=OfertaRepository::class)
 * @Vich\Uploadable()
 */
class Oferta
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nazwa_oferty;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $opis_oferty;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_obrazka;

    /**
     * @Vich\UploadableField(mapping="obraz", fileNameProperty="url_obrazka")
     */
    private $obrazek;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="float")
     */
    private $cena_za_kg;

    public function __construct()
    {
        $this->updatedAt=new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNazwaOferty(): ?string
    {
        return $this->nazwa_oferty;
    }

    public function setNazwaOferty(string $nazwa_oferty): self
    {
        $this->nazwa_oferty = $nazwa_oferty;

        return $this;
    }

    public function getOpisOferty(): ?string
    {
        return $this->opis_oferty;
    }

    public function setOpisOferty(?string $opis_oferty): self
    {
        $this->opis_oferty = $opis_oferty;

        return $this;
    }

    public function getUrlObrazka(): ?string
    {
        return $this->url_obrazka;
    }

    public function setUrlObrazka(?string $url_obrazka): self
    {
        $this->url_obrazka = $url_obrazka;

        return $this;
    }

    public function getObrazek()
    {
        return $this->obrazek;
    }

    public function setObrazek( $obrazek): void
    {
        $this->obrazek = $obrazek;

        if($obrazek instanceof UploadedFile)
        {
            $this->setUpdatedAt(new \DateTime());
        }
    }
    public function getUpdatedAt():  ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt)
    {
        $this->updatedAt=new \DateTime();
        return $this;
    }

    public function __toString()
    {
        return $this->nazwa_oferty;
    }

    public function getCenaZaKg(): ?float
    {
        return $this->cena_za_kg;
    }

    public function setCenaZaKg(float $cena_za_kg): self
    {
        $this->cena_za_kg = $cena_za_kg;

        return $this;
    }


}

src/Entity/Plan.php
<?php

namespace App\Entity;

use App\Repository\PlanRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlanRepository::class)
 */
class Plan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $poniedzialek;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $wtorek;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sroda;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $czwartek;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $piatek;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $pracownik_id_pracownika;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoniedzialek(): ?string
    {
        return $this->poniedzialek;
    }

    public function setPoniedzialek(?string $poniedzialek): self
    {
        $this->poniedzialek = $poniedzialek;

        return $this;
    }

    public function getWtorek(): ?string
    {
        return $this->wtorek;
    }

    public function setWtorek(?string $wtorek): self
    {
        $this->wtorek = $wtorek;

        return $this;
    }

    public function getSroda(): ?string
    {
        return $this->sroda;
    }

    public function setSroda(?string $sroda): self
    {
        $this->sroda = $sroda;

        return $this;
    }

    public function getCzwartek(): ?string
    {
        return $this->czwartek;
    }

    public function setCzwartek(?string $czwartek): self
    {
        $this->czwartek = $czwartek;

        return $this;
    }

    public function getPiatek(): ?string
    {
        return $this->piatek;
    }

    public function setPiatek(?string $piatek): self
    {
        $this->piatek = $piatek;

        return $this;
    }

    public function getPracownikIdPracownika(): ?User
    {
        return $this->pracownik_id_pracownika;
    }

    public function setPracownikIdPracownika(?User $pracownik_id_pracownika): self
    {
        $this->pracownik_id_pracownika = $pracownik_id_pracownika;

        return $this;
    }
}

src/Entity/Zamowienie.php
<?php

namespace App\Entity;

use App\Repository\ZamowienieRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ZamowienieRepository::class)
 */
class Zamowienie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $data_przyjecia;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $data_oddania;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=Oferta::class)
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $oferta_id_oferty;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $user_id_usera;

    /**
     * @ORM\Column(type="float")
     */
    private $waga;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDataPrzyjecia(): ?\DateTimeInterface
    {
        return $this->data_przyjecia;
    }

    public function setDataPrzyjecia(\DateTimeInterface $data_przyjecia): self
    {
        $this->data_przyjecia = $data_przyjecia;

        return $this;
    }

    public function getDataOddania(): ?\DateTimeInterface
    {
        return $this->data_oddania;
    }

    public function setDataOddania(?\DateTimeInterface $data_oddania): self
    {
        $this->data_oddania = $data_oddania;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getOfertaIdOferty(): ?Oferta
    {
        return $this->oferta_id_oferty;
    }

    public function setOfertaIdOferty(?Oferta $oferta_id_oferty): self
    {
        $this->oferta_id_oferty = $oferta_id_oferty;

        return $this;
    }

    public function getUserIdUsera(): ?User
    {
        return $this->user_id_usera;
    }

    public function setUserIdUsera(?User $user_id_usera): self
    {
        $this->user_id_usera = $user_id_usera;

        return $this;
    }
    public function __toString()
    {
        return ''.$this->id;
    }

    public function getWaga(): ?float
    {
        return $this->waga;
    }

    public function setWaga(float $waga): self
    {
        $this->waga = $waga;

        return $this;
    }
}

src/Entity/ZamowieniePracownik.php
<?php

namespace App\Entity;

use App\Repository\ZamowieniePracownikRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ZamowieniePracownikRepository::class)
 */
class ZamowieniePracownik
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $pracownik_id_pracownika;

    /**
     * @ORM\ManyToOne(targetEntity=Zamowienie::class)
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $zamowienie_id_zamowienia;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPracownikIdPracownika(): ?User
    {
        return $this->pracownik_id_pracownika;
    }

    public function setPracownikIdPracownika(?User $pracownik_id_pracownika): self
    {
        $this->pracownik_id_pracownika = $pracownik_id_pracownika;

        return $this;
    }

    public function getZamowienieIdZamowienia(): ?Zamowienie
    {
        return $this->zamowienie_id_zamowienia;
    }

    public function setZamowienieIdZamowienia(?Zamowienie $zamowienie_id_zamowienia): self
    {
        $this->zamowienie_id_zamowienia = $zamowienie_id_zamowienia;

        return $this;
    }
}

templates/worker/zad_do_realizacji.html.twig
{% extends 'menu/customer.html.twig' %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('/css/loader.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
    {{ parent() }}

    <style>
        .underLineData{

        }
    </style>

    <div class="container align-items-center">
        <div class="row">
            {% for zadanie in zadania %}
                {% if zadanie.status == 0 %}
                    <div class="card-group ml-auto mr-auto mt-2 mb-2">
                        <div id="{{ zadanie.id }}" class="card rounded-lg" style="width: 18rem;">
                            <img class="card-img-top mx-auto mt-3 mb-0" style="width: 16rem; height: 10rem;"
                                 src="/build/{{ zadanie.ofertaIdOferty.urlObrazka }}"
                                 alt="{{ zadanie.ofertaIdOferty }}">
                            <div class="card-body" style="margin-left: auto; margin-right: auto;">
                                <h4 class="card-title">{{ zadanie.ofertaIdOferty }}</h4>
                            </div>
                            <label class="card-text" style="padding-bottom: 0;">ID:</label>
                            <span style="border-bottom: solid gold; border-width: 1px; margin-left: 10px; margin-right: 10px; padding-left: 30px; font-size: 22px"> {{ zadanie.id }}</span>
                            <p class="card-text pl-2">Data przyjęcia: {{ zadanie.dataPrzyjecia.format('d-m-yy') }}</p>
                            <p class="card-text pb-2 pl-2">Masa: {{ zadanie.waga }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div style="position: fixed; bottom: 70px; right: 60px;">
            {#<a class="btn btn-primary btn-md float-lg-right mb-5 mr-n5" href="#">Przypisz sobie</a>#}
            {% if zadania|length == 0 %}
            {% else %}
                <button id="myBtn" class="btn btn-danger btn-lg">Przypisz do mnie</button>
            {% endif %}
        </div>
    </div>

    <div id="processModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog-centered" role="document" style="width: 30%; margin-right: auto; margin-left: auto;">
            <div id="modalContentAlert" class="modal-content" style="background: transparent; border: none">
                <div id="processingModal" class="modal-body">
                    <div class="loader"></div>
                </div>
                <div id="successModal" class="modal-body" style="backdrop-filter: blur(5px)">
                    <div class="display-3 text-white">Dodano</div>
                </div>
                <div id="errorModal" class="modal-body" style="backdrop-filter: blur(5px)">
                    <div class="display-3 text-white">Nie dodano</div>
                </div>
                <div id="acceptModal" class="modal-footer" style="backdrop-filter: blur(5px)">
                    <button id="acceptButton" type="button" class="btn btn-success">Akceptuj</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        let test=[];
        let clickedCard=[];
        {% for zadanie in zadania %}
        {% if zadanie.status == 0 %}
            test.push({{ zadanie }});
        {% endif %}
        {% endfor %}
        /*document.getElementById("myBtn").addEventListener("click", function () {
            document.getElementById("arrayShow").innerHTML=test.toString();
        });*/

        let karty = document.getElementsByClassName("card");
        let getCardId = function () {
            let cardId = this.getAttribute("id");
            let cardIdIndex = clickedCard.indexOf(cardId);
            if (cardIdIndex !== -1){
                clickedCard.splice(cardIdIndex, 1);
                document.getElementById(cardId).style.backgroundColor="white";
            }
            else{
                clickedCard.push(cardId);
                document.getElementById(cardId).style.backgroundColor="aqua";
            }
            //zmiana koloru

            //zmiana koloru
            document.getElementById("clickedCards").innerHTML=clickedCard.toString();
        };
        Array.from(karty).forEach(function (karta){
            karta.addEventListener("click", getCardId);
        });


        $(document).ready(function(){
            $("#secBtn").click(function(){
                $("#ajaxResponse").text("ELo");
            });
        });

        $(document).ready(function (){
            $("#myBtn").click(function (){

                $('#successModal').hide() //ukrycie napisu pomyślnego przypisania w modalu
                $('#acceptModal').hide()  //ukrycie przycisku akceptuj w modalu
                $('#errorModal').hide() //ukrycie napisu o bledzie w modalu
                $('#processModal').toggle() //wlaczenie modalu

                $.ajax({
                    type: 'POST',
                    url: '{{ path('zadania') }}',
                    data:{
                        zadanka: clickedCard
                    },
                    complete: function(response){
                        $('#processingModal').hide() //ukrycie loadera
                        $('#acceptModal').show()    //pokazanie przycisku akceptuj w modalu
                    },
                    success: function (response){
                        $('#modalContentAlert').css('background', 'rgba(61,219,76,0.5)')
                        $('#successModal').show()   //pokazanie napisu pomyslnego przypisania modalu
                    },
                    error: function (response){
                        $('#modalContentAlert').css('background', 'rgba(219,25, 21,0.5)')
                        $('#errorModal').show()
                    }
                });
            });
        });

        $(document).ready(function (){
            $('#acceptButton').click(function (){
                location.reload()
            })
        });
    </script>
{% endblock %}

templates/worker/zrealizowane_zamowienia.html.twig
{% extends 'menu/customer.html.twig' %}
{% block head %}
    {% block stylesheets %}
        {{ parent() }}
        <style>
            .card:hover
            {
                transform: scale(1.1);
                box-shadow: 5px 5px 15px rgba(0,0,0,0.9);
                z-index: 3;
            }
            .card
            {
                z-index: 1;
                transition: 0.5s ease;
                cursor: pointer;
                display: grid;
                border-radius: 18px;
                margin: 15px;
                background: #371f1f;
                color: white;
            }

            .image
            {
                border-top-left-radius: 15px;
                border-top-right-radius: 15px;
            }
            .more
            {
                display: none;
                -webkit-transition: height 20s;
                overflow: hidden;
            }
            .top
            {
                display: inline-block;
                width: 4em;
                height: 4em;
                border: 0.5em solid #b79545;
                border-radius: 50%;
                align-items: center;
                justify-content: center;
                margin-left: 37%;
                margin-top: 1%;

            }
            .top:after
            {
                content: '';
                display: inline-block;
                margin-top: 1.1em;
                width: 1.4em;
                height: 1.4em;
                border-top: 0.5em solid #af9958;
                border-right: 0.5em solid #e5d18b;
                -moz-transform: rotate(-45deg);
                -webkit-transform: rotate(-45deg);
                transform: rotate(-45deg);
                text-align: center;
                justify-content: center;

            }

            a:hover .top
            {
                border: 0.5em solid #cfa057;
            }

            a:hover .top:after
            {
                border-top: 0.5em solid #eebd5e;
                border-right: 0.5em solid #ffe5a4;
            }

            .bottom {
                display: inline-block;
                width: 4em;
                height: 4em;
                border: 0.5em solid #aa9269;
                border-radius: 50%;
                margin-left: 0.75em;
                margin-left: 39%;
                margin-top: 1%;
            }

            .bottom:after {
                content: '';
                display: inline-block;
                margin-top: 0.6em;
                width: 1.4em;
                height: 1.4em;
                border-top: 0.5em solid #af9958;
                border-right: 0.5em solid #e5d18b;
                -moz-transform: rotate(135deg);
                -webkit-transform: rotate(135deg);
                transform: rotate(135deg);
            }

            a:hover .bottom
            {
                border: 0.5em solid #cfa057;
            }

            a:hover .bottom:after
            {
                border-top: 0.5em solid #eebd5e;
                border-right: 0.5em solid #ffe5a4;
            }


        </style>
    {% endblock%}
{% endblock %}
{% block body %}
    {{ parent() }}
    <div class="row">
    {% for zamowienie_pracownik in zamowienia_pracownika %}
        {% if zamowienie_pracownik.pracownikIdPracownika.email == user and zamowienie_pracownik.zamowienieIdZamowienia.status==2 %}
            <div class="card-group ml-auto mr-auto mt-2 mb-2" style=" border-radius: 18px;">
                <div id="{{ zamowienie_pracownik.zamowienieIdZamowienia.id }}" class="card" style="width: 18rem;">
                    {% if zamowienie_pracownik.zamowienieIdZamowienia.ofertaIdOferty.urlObrazka !=null %}
                        <div class="card-img-top">
                            <img class="image" style="width: 18rem; height: 12rem " src="/build/{{ zamowienie_pracownik.zamowienieIdZamowienia.ofertaIdOferty.urlObrazka }}" alt="{{ zamowienie_pracownik.zamowienieIdZamowienia.ofertaIdOferty.nazwaOferty }}">
                        </div>
                    {% endif%}
                    <div class="card-body " >
                        <div class="card-title pl-2" style="text-align: center; font-family: Cambria; color: goldenrod; font-weight: 1000;">{{ zamowienie_pracownik.zamowienieIdZamowienia.ofertaIdOferty.nazwaOferty }}</div>
                        <div class="card-text pl-2 dane" ><b>Dane ciasta:</b></div>
                        <div class="card-text pl-2 dane" >Cena: {{ zamowienie_pracownik.zamowienieIdZamowienia.ofertaIdOferty.cenaZaKg * zamowienie_pracownik.zamowienieIdZamowienia.waga }}zł</div>
                        <div class="card-text pl-2 dane" >Waga: {{ zamowienie_pracownik.zamowienieIdZamowienia.waga }}kg</div>
                        <div class="card-text pl-2 dane" > {{ zamowienie_pracownik.zamowienieIdZamowienia.dataPrzyjecia.format('d.m.yy') }} - {{ zamowienie_pracownik.zamowienieIdZamowienia.dataOddania.format('d.m.yy') }}</div>
                        <div class="card-title pl-2 " style="margin-right: auto; margin-left: auto"><img src="/build/ozdoby.png" alt="ozdoba" width="250px"></div>
                        <span id="{{ zamowienie_pracownik.zamowienieIdZamowienia.id }}dots"></span>

                        <span id="{{ zamowienie_pracownik.zamowienieIdZamowienia.id }}more" class="more">
                                <div class="card-text pl-2"><b>Dane klienta:</b></div>
                                <div class="card-text pl-2">{{ zamowienie_pracownik.zamowienieIdZamowienia.userIdUsera.name }} {{ zamowienie_pracownik.zamowienieIdZamowienia.userIdUsera.surname }}</div>
                                <div class="card-text pl-2">Email: {{ zamowienie_pracownik.zamowienieIdZamowienia.userIdUsera.email }}</div>
                                <div class="card-text pl-2">Telefon: {{ zamowienie_pracownik.zamowienieIdZamowienia.userIdUsera.tel }}</div>
                        </span>
                        <a href="javascript:void(0)" style="margin-right: auto; margin-left: auto"><button class="bottom" onclick="myFunction({{ zamowienie_pracownik.zamowienieIdZamowienia.id }})" id="{{ zamowienie_pracownik.zamowienieIdZamowienia.id }}myBtn"></button></a>

                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}

    <script>

        function myFunction(shID) {
            let dots = document.getElementById(shID+"dots");
            let moreText = document.getElementById(shID+"more");
            let btnText = document.getElementById(shID+"myBtn");
            if (dots.style.display === "none") {
                dots.style.display = "inline";
                /*btnText.innerHTML = "Read more";*/
                btnText.classList.add('bottom');
                btnText.classList.remove('top');
                moreText.style.display = "none";
            } else {
                dots.style.display = "none";
                /*btnText.innerHTML = "Read less";*/
                btnText.classList.remove('bottom');
                btnText.classList.add('top');
                moreText.style.display = "inline";
            }
        }
    </script>
{% endblock %}