src/Entity/Oferta.php
<?php

namespace App\Entity;

use App\Repository\OfertaRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=OfertaRepository::class)
 * @Vich\Uploadable()
 */
class Oferta
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nazwa_oferty;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $opis_oferty;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_obrazka;

    /**
     * @Vich\UploadableField(mapping="obraz", fileNameProperty="url_obrazka")
     */
    private $obrazek;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="float")
     */
    private $cena_za_kg;

    public function __construct()
    {
        $this->updatedAt=new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNazwaOferty(): ?string
    {
        return $this->nazwa_oferty;
    }

    public function setNazwaOferty(string $nazwa_oferty): self
    {
        $this->nazwa_oferty = $nazwa_oferty;

        return $this;
    }

    public function getOpisOferty(): ?string
    {
        return $this->opis_oferty;
    }

    public function setOpisOferty(?string $opis_oferty): self
    {
        $this->opis_oferty = $opis_oferty;

        return $this;
    }

    public function getUrlObrazka(): ?string
    {
        return $this->url_obrazka;
    }

    public function setUrlObrazka(?string $url_obrazka): self
    {
        $this->url_obrazka = $url_obrazka;

        return $this;
    }

    public function getObrazek()
    {
        return $this->obrazek;
    }

    public function setObrazek( $obrazek): void
    {
        $this->obrazek = $obrazek;

        if($obrazek instanceof UploadedFile)
        {
            $this->setUpdatedAt(new \DateTime());
        }
    }
    public function getUpdatedAt():  ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt)
    {
        $this->updatedAt=new \DateTime();
        return $this;
    }

    public function __toString()
    {
        return $this->nazwa_oferty;
    }

    public function getCenaZaKg(): ?float
    {
        return $this->cena_za_kg;
    }

    public function setCenaZaKg(float $cena_za_kg): self
    {
        $this->cena_za_kg = $cena_za_kg;

        return $this;
    }


}

src/Controller/OfertaController.php
<?php


namespace App\Controller;


use App\Entity\Oferta;
use App\Entity\Zamowienie;
use Doctrine\DBAL\Types\FloatType;
use Doctrine\DBAL\Types\IntegerType;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Validation;

class OfertaController extends AbstractController
{
    /**
     * @Route ("/oferta", name="oferta")
     */
    public function oferta()
    {
        $token = $this->get('security.token_storage')->getToken()->getUser();
        $repository = $this->getDoctrine()->getRepository(Oferta::class);
        $oferta = $repository->findAll();
        return $this->render('oferta/oferta.html.twig', ['oferta'=>$oferta, 'user'=>$token]);

    }
    /**
     * @Route("/oferta/{slug}", name="blog_post")
     */
    public function show(int $slug, Request $request)
    {
        $token = $this->get('security.token_storage')->getToken()->getUser();
        $repository=$this->getDoctrine()->getRepository(Oferta::class);
        $oferta=$repository->findBy(array('id'=>$slug));

        $repository1=$this->getDoctrine()->getRepository(Oferta::class);
        $zamowienie=$repository->find($slug);

        $task=new Zamowienie();
        $task->setDataPrzyjecia(new \DateTime('today'));
        $task->setOfertaIdOferty($oferta[0]);
        $task->setStatus(0);
        $task->setUserIdUsera($token);


        $form=$this->createFormBuilder($task)
           /* ->add('data_przyjecia', DateType::class, ['disabled'=>'on'])*/
            ->add('waga', NumberType::class, ['label'=>'Waga (kg)', 'required' => true ])
            /*->add('status', NumberType::class, ['disabled'=>'on'])*/
            /*->add('user_id_usera', TextType::class, ['disabled'=>'on'])*/
           /* ->add('oferta_id_oferty', TextType::class, ['disabled'=>'on', 'label'=>'Nazwa ciasta '])*/
            ->add('Dodaj', SubmitType::class, ['label' => ' Dodaj do koszyka'])
            ->getForm();
        ;
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $task = $form->getData();

            // ... perform some action, such as saving the task to the database
            // for example, if Task is a Doctrine entity, save it!
            //
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('moje_zamowienia');
        }

        return $this->render('oferta/zamowienie.html.twig', ['slug'=>$slug, 'oferty'=>$oferta, 'form'=>$form->createView(), 'user'=>$token, 'zamowienie'=>$zamowienie]);
    }

}

templates/oferta/oferta.html.twig
{% extends "menu/customer.html.twig" %}

{% block title %}Index{% endblock %}
{% block head %}
    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        .card:hover
        {
            transform: scale(1.1);
            box-shadow: 5px 5px 15px rgba(0,0,0,0.9);
            z-index: 3;

        }

        .card
        {
            z-index: 1;
            transition: 0.5s ease;
            cursor: pointer;
            display: grid;
            border-radius: 18px;
            margin: 15px;
            background: #371f1f;
            color: white;
        }

        .con:hover .overlay {
            opacity: 0.9;
        }
        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 60%;
            left: 35%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }

        .image {
            opacity: 1;
            display: block;
            width: 100%;
            height: auto;
            transition: .5s ease;
            backface-visibility: hidden;
        }
        .col:hover .image {
            opacity: 0.3;
        }

        .col:hover .middle {
            opacity: 1;
        }

        .text {
            background-color: #87523a;
            color: white;
            font-size: 16px;
            padding: 13px 32px;
        }



    </style>
    {% endblock %}

    {% block javascripts %}
        {{ parent() }}

    <script>

    </script>
    {% endblock %}
{% endblock %}
{% block body %}
    {{ parent() }}
    {#{{ dump(oferta) }}#}

    <div class="container align-items-center" style="margin-left: auto; margin-right: auto; margin-top: -50px;">
        <div class="row">
            {% for ofert in oferta%}
                <div class="card-group ml-auto mr-auto mt-2 mb-2" style=" border-radius: 18px;">
                    <div class="card" style="width: 18rem">
                        {% if  ofert.urlObrazka !=null %}
                            <div class="card-img-top">
                                <img class="image" style="width: 18rem; height: 12rem; border-top-left-radius: 15px; border-top-right-radius: 15px " src="/build/{{ ofert.urlObrazka }}" alt="{{ ofert.urlObrazka }}">
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <div class="card-title pl-2" style="text-align: center; font-family: Cambria; color: goldenrod; font-weight: 1000;">{{ ofert.nazwaOferty }}</div>
                            <div class="card-text pl-2">{{ ofert.opisOferty|raw }}</div>{#dodanie raw powoduje generowanie surowego htmla#}
                            <div class="card-text pl-2"><b>Cena za kg:</b> {{ ofert.cenaZaKg }} </div>

                        {% if user!="anon." %}
                            {#<div class="middle">#}
                                <a href="{{ path('blog_post', {slug: ofert.id }) }}" style="color: #fb8d8d">Dodaj</a> {#przekazanie slug do OfertaController do metody show#}
                            {#</div>#}
                        {% endif%}
                        <div class="card-title pl-2" style="margin-right: auto; margin-left: auto"><img src="/build/ozdoby.png" alt="ozdoba" width="250px"></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>






{% endblock %}

templates/oferta/zamowienie.html.twig
{% extends "menu/customer.html.twig" %}

{% block title %}Index{% endblock %}
{% block head %}
    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
            .karta
            {
                align-items: center;
                margin-right: auto;
                margin-left: auto;
                background: radial-gradient(circle, rgba(255,192,203 ,1 ) 0%, rgba(141,12,215,1) 100%);
                text-align: center;
                width: 30%;
                min-width: 300px;
                border-radius: 2%;
                padding: 2% 0%;
                transform: scale(1.1);
                transition: 1s ease;


            }

            .karta:hover
            {
                transform: scale(1.1);
                box-shadow: 5px 5px 15px rgba(0,0,0,0.9);

            }

            /*.napis
            {
                text-align: center;
                background: #90c6f1;
            }*/

            .foo
            {
                background: #ff91e8;
                padding: 1% 2%;
                margin: 2%;
                transition: 1s ease;
            }
            .foo:hover
            {
                transform: scale(1.03);
                /*box-shadow: 5px 5px 15px rgba(0,0,0,0.9);*/
            }

            .card:hover
            {
                transform: scale(1.1);
                box-shadow: 5px 5px 15px rgba(0,0,0,0.9);
                z-index: 3;
            }
            .card
            {
                z-index: 1;
                transition: 0.5s ease;
                cursor: pointer;
                display: grid;
                border-radius: 15px;
                margin: 15px;
                background: #371f1f;
                color: white;
            }
            .con:hover .overlay {
                opacity: 0.9;
            }
            .middle {
                transition: .5s ease;
                opacity: 0;
                position: absolute;
                top: 60%;
                left: 35%;
                transform: translate(-50%, -50%);
                -ms-transform: translate(-50%, -50%);
                text-align: center;
            }
            .napis
            {
                border: none;
                border-bottom: 1px solid #f1a6de;
                background: transparent;
                text-align: center;
                outline: none;
            }

            .image {
                opacity: 1;
                display: block;
                height: auto;
                transition: .5s ease;
                backface-visibility: hidden;

            }
            .col:hover .image {
                opacity: 0.3;
            }

            .col:hover .middle {
                opacity: 1;
            }

            .text {
                background-color: #87523a;
                color: white;
                font-size: 16px;
                padding: 13px 32px;
            }


        </style>
    {% endblock %}

    {% block javascripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endblock %}
{% endblock %}
{% block body %}
    {{ parent() }}
<div class="karta" style="align-items: center; margin-right: auto; margin-left: auto; background: radial-gradient(circle, rgba(255,192,203 ,1 ) 0%, rgba(141,12,215,1) 100%); text-align: center; width: 30%;min-width: 300px; border-radius: 2%; padding: 2% 0%" >

    {% for oferta in oferty%}
        <div >
        {% if oferta.id ==  slug    %}
            <img src="/build/{{ oferta.getUrlObrazka() }}"   style="height: 250px; width: 250px ; margin-right: auto; margin-left: auto" class="image">
        {% endif %}
                <div style="text-align: center; font-family: Cambria; color: #b336f1; font-weight: 1000; font-size: 20px">{{ oferta.nazwaOferty }}</div>
                {{ form_start(form) }}
                <table style="margin-left: auto; margin-right: auto">

                    <tr>
                        <td >
                            Cena za kilogram
                        </td>
                        <td>
                            {{ oferta.cenaZaKg }}zł
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form_label(form.children['waga']) }}
                        </td>
                        <td class="input_waga">
                            {{ form_widget(form.children['waga'], {'attr': {'class': 'napis', 'size' : '8'}}) }}
                        </td>

                    </tr>

                </table>
                {%  if form_label(form.children['waga'])<0 %}
                    <b style=" color: red">Waga musi być liczbą dodatnią </b>
                {% elseif form_errors(form.children['waga']) !=null %}
                    <b style="color: red">Waga musi być liczbą nieujemną!!!</b><br>
                {% endif %}

                <div>{{ form_widget(form.children['Dodaj'], {'attr': {'class': 'foo'}}) }}</div>

                {{ form_end(form) }}
            </div>

    {% endfor %}
</div>
{% endblock %}